STATE_CLASSIFYING_DOCS = '1_CLASSIFYING_DOCS'
STATE_CLASSIFYING_DOCS_KO = '2_CLASSIFYING_DOCS_KO'
STATE_CLASSIFYING_DOCS_OK = '3_CLASSIFYING_DOCS_OK'

STATE_SELECTING_REFERENCE_RESPONSE = '4_SELECTING_REFERENCE_RESPONSE'
STATE_SELECTING_REFERENCE_RESPONSE_KO = '5_SELECTING_REFERENCE_RESPONSE_KO'
STATE_SELECTING_REFERENCE_RESPONSE_OK = '6_SELECTING_REFERENCE_RESPONSE_OK'

STATE_CHUNKING_DOCS = '7_CHUNKING_DOCS'
STATE_CHUNKING_DOCS_KO = '8_CHUNKING_DOCS_KO'
STATE_CHUNKING_DOCS_OK = '9_CHUNKING_DOCS_OK'

STATE_CREATING_KB = '10_CREATING_KB'
STATE_CREATING_KB_KO = '11_CREATING_KB_KO'
STATE_CREATING_KB_OK = '12_CREATING_KB_OK'

STATE_SYNCING_KB = '13_SYNCING_KB'
STATE_SYNCING_KB_KO = '14_SYNCING_KB_KO'
STATE_SYNCING_KB_OK = '15_SYNCING_KB_OK'

STATE_GENERATING_RESPONSE = '16_GENERATING_RESPONSE'
STATE_GENERATING_RESPONSE_KO = '17_GENERATING_RESPONSE_KO'
STATE_GENERATING_RESPONSE_OK = '18_GENERATING_RESPONSE_OK'

ALL_STATES = sorted([
    STATE_CLASSIFYING_DOCS,
    STATE_CLASSIFYING_DOCS_KO,
    STATE_CLASSIFYING_DOCS_OK,

    STATE_SELECTING_REFERENCE_RESPONSE,
    STATE_SELECTING_REFERENCE_RESPONSE_KO,
    STATE_SELECTING_REFERENCE_RESPONSE_OK,

    STATE_CHUNKING_DOCS,
    STATE_CHUNKING_DOCS_KO,
    STATE_CHUNKING_DOCS_OK,

    STATE_CREATING_KB,
    STATE_CREATING_KB_KO,
    STATE_CREATING_KB_OK,

    STATE_SYNCING_KB,
    STATE_SYNCING_KB_KO,
    STATE_SYNCING_KB_OK,

    STATE_GENERATING_RESPONSE,
    STATE_GENERATING_RESPONSE_KO,
    STATE_GENERATING_RESPONSE_OK
])

TAG_CATEGORY = 'classification'
TAG_PAGE_COUNT = 'page-count'
TAG_SKIP_CLASSIFICATION = 'skipClassification'
TAG_LAST_CLASSIFICATION_ETAG = 'lastClassificationEtag'

APPLICANT_RESPONSE_CATEGORIES = ['technical_response', 'administrative_response']

PROJECT_CATEGORIES = [
    "technical_specifications",
    "technical_specifications_modifications",
    "legal_clauses",
    "legal_clauses_modifications",
    "economic_requirements"
]
